Repository googleapis/python-area120-tables, pull requests merged in 2021-04, with the labels that each got.

#25 feat: Added ListWorkspaces, GetWorkspace, BatchDeleteRows APIs
  .coveragerc
  .github/header-checker-lint.yml
  .gitignore
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/samples/python3.6/periodic-head.cfg
  .kokoro/samples/python3.7/periodic-head.cfg
  .kokoro/samples/python3.8/periodic-head.cfg
  .kokoro/test-samples-against-head.sh
  .kokoro/test-samples-impl.sh
  .pre-commit-config.yaml
  .trampolinerc
  CONTRIBUTING.rst
  MANIFEST.in
  area120-tables-v1alpha1-py.tar.gz
  docs/tables_v1alpha1/services.rst
  docs/tables_v1alpha1/tables_service.rst
  docs/tables_v1alpha1/types.rst
  google/area120/tables/__init__.py
  google/area120/tables_v1alpha1/__init__.py
  google/area120/tables_v1alpha1/services/tables_service/async_client.py
  google/area120/tables_v1alpha1/services/tables_service/client.py
  google/area120/tables_v1alpha1/services/tables_service/pagers.py
  google/area120/tables_v1alpha1/services/tables_service/transports/base.py
  google/area120/tables_v1alpha1/services/tables_service/transports/grpc.py
  google/area120/tables_v1alpha1/services/tables_service/transports/grpc_asyncio.py
  google/area120/tables_v1alpha1/types/__init__.py
  google/area120/tables_v1alpha1/types/tables.py
  noxfile.py
  renovate.json
  setup.py
  synth.metadata
  synth.py
  testing/constraints-3.6.txt
  testing/constraints-3.9.txt
  tests/unit/gapic/tables_v1alpha1/__init__.py
  tests/unit/gapic/tables_v1alpha1/test_tables_service.py
Labels: api: area120tables, automerge, cla: yes, context: partial

#28 chore: start tracking obsolete files
  synth.metadata
Labels: api: area120tables, cla: yes, context: full

#29 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: area120tables, automerge, cla: yes, context: full

#30 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: area120tables, cla: yes, context: full, samples

#32 chore: prevent normalization of semver versioning
  setup.py
Labels: api: area120tables, cla: yes

#33 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  owlbot.py
  synth.metadata
Labels: api: area120tables, automerge, cla: yes

#35 chore(revert): revert preventing normalization
  setup.py
Labels: api: area120tables, cla: yes
